import { Router, Request, Response } from 'express';
import { Firestore, FieldValue } from 'firebase-admin/firestore';
import { randomBytes } from 'crypto';
import { adminAuth } from '../firebaseAdmin';
import { authenticateFirebase } from '../middleware/authenticateFirebase';
import { requireRole } from '../middleware/requireRole';

export function createUsersRouter(db: Firestore | null): Router {
  const router = Router();

  // 1. Create New Staff Account (Admin Only) via Firebase Admin SDK
  router.post('/create', authenticateFirebase, requireRole('ADMIN'), async (req: Request, res: Response) => {
    let authUserRecord: any = null;
    let isNewlyCreatedInAuth = false;

    try {
      const {
        email,
        password,
        displayName,
        phone,
        role = 'SALES',
        branchId = 'CN01',
        assignedBranchIds = ['CN01'],
        workplaceAddresses = [],
        notes = ''
      } = req.body;

      if (!email || !displayName) {
        return res.status(400).json({
          success: false,
          error: 'MISSING_FIELDS',
          message: 'Vui lòng cung cấp đầy đủ Email và Họ tên nhân viên.'
        });
      }

      const emailNormalized = email.trim().toLowerCase();
      const isAutoGeneratedPassword = !password || password.length < 6;
      const initialPassword = isAutoGeneratedPassword
        ? randomBytes(16).toString('hex') + 'A1!'
        : password;

      // 1A. Check if user already exists in Firebase Auth, or create
      try {
        authUserRecord = await adminAuth.getUserByEmail(emailNormalized);
        if (password && password.length >= 6) {
          await adminAuth.updateUser(authUserRecord.uid, {
            password,
            displayName
          });
        }
      } catch (err: any) {
        if (err.code === 'auth/user-not-found') {
          // Create new user in Firebase Auth with strong random password
          authUserRecord = await adminAuth.createUser({
            email: emailNormalized,
            password: initialPassword,
            displayName,
            phoneNumber: phone && phone.startsWith('+') ? phone : undefined
          });
          isNewlyCreatedInAuth = true;
        } else {
          throw err;
        }
      }

      const uid = authUserRecord.uid;

      // 1B. Set Custom User Claims on Firebase Auth
      await adminAuth.setCustomUserClaims(uid, {
        role: role.toUpperCase(),
        branchId
      });

      // 1C. Create or Update Document in Firestore 'users' collection with ID = uid
      const userData = {
        id: uid,
        uid,
        email: emailNormalized,
        displayName,
        phone: phone || '',
        role: role.toUpperCase(),
        branchId,
        assignedBranchIds: assignedBranchIds.length > 0 ? assignedBranchIds : [branchId],
        workplaceAddresses,
        active: true,
        mustChangePassword: isAutoGeneratedPassword,
        notes,
        createdAt: new Date().toISOString().split('T')[0],
        updatedAt: FieldValue.serverTimestamp()
      };

      if (db) {
        try {
          await db.collection('users').doc(uid).set(userData, { merge: true });
          
          // Also ensure a mirror record exists in staff collection for attendance matching
          await db.collection('staff').doc(uid).set({
            id: uid,
            uid,
            name: displayName,
            email: emailNormalized,
            phone: phone || '',
            role: role.toUpperCase(),
            branchId,
            active: true,
            updatedAt: FieldValue.serverTimestamp()
          }, { merge: true });
        } catch (dbErr) {
          // Rollback newly created Auth user on DB failure to avoid orphaned accounts
          if (isNewlyCreatedInAuth && uid) {
            try {
              await adminAuth.deleteUser(uid);
            } catch (rollbackErr) {
              console.error('[Rollback Auth User Error]:', rollbackErr);
            }
          }
          throw dbErr;
        }
      }

      return res.json({
        success: true,
        message: 'Tài khoản nhân viên đã được cấp phép đăng nhập thành công.',
        user: userData
      });
    } catch (error: any) {
      console.error('[Create User Error]:', error);
      return res.status(400).json({
        success: false,
        error: error.code || 'USER_CREATION_FAILED',
        message: error.message || 'Không thể tạo tài khoản nhân viên.'
      });
    }
  });

  // 2. Set / Update Role & Branch (Admin Only) with Token Revocation
  router.post('/update-role', authenticateFirebase, requireRole('ADMIN'), async (req: Request, res: Response) => {
    try {
      const { uid, role, branchId, active } = req.body;
      if (!uid) {
        return res.status(400).json({ success: false, error: 'MISSING_UID', message: 'Thiếu UID người dùng.' });
      }

      // Update Firebase Auth Claims
      if (role || branchId) {
        const currentAuth = await adminAuth.getUser(uid);
        const currentClaims = currentAuth.customClaims || {};
        await adminAuth.setCustomUserClaims(uid, {
          ...currentClaims,
          ...(role ? { role: role.toUpperCase() } : {}),
          ...(branchId ? { branchId } : {})
        });
      }

      // If deactivated or role/branch changed, revoke all refresh tokens immediately
      try {
        await adminAuth.revokeRefreshTokens(uid);
      } catch (revokeErr) {
        console.warn('[Revoke Tokens Warn]:', revokeErr);
      }

      // Update Firestore Document & Staff Mirror
      if (db) {
        const updatePayload: any = {
          updatedAt: FieldValue.serverTimestamp()
        };
        if (role) updatePayload.role = role.toUpperCase();
        if (branchId) updatePayload.branchId = branchId;
        if (typeof active === 'boolean') updatePayload.active = active;

        await db.collection('users').doc(uid).update(updatePayload);

        // Synchronize Staff Mirror Document
        const staffRef = db.collection('staff').doc(uid);
        const staffSnap = await staffRef.get();
        if (staffSnap.exists) {
          await staffRef.update(updatePayload);
        }
      }

      return res.json({
        success: true,
        message: 'Đã cập nhật quyền hạn, chi nhánh và thu hồi token phiên cũ thành công.'
      });
    } catch (error: any) {
      console.error('[Update Role Error]:', error);
      return res.status(400).json({
        success: false,
        error: error.code || 'ROLE_UPDATE_FAILED',
        message: error.message || 'Lỗi cập nhật vai trò người dùng.'
      });
    }
  });

  return router;
}
