export type CanonicalRole = 'ADMIN' | 'REGIONAL_MANAGER' | 'MANAGER' | 'STORE_MANAGER' | 'SALES' | 'SALE_ONLINE' | 'CUSTOMER_CARE' | 'TECHNICIAN' | 'TECH_LEAD' | 'CASHIER' | 'WAREHOUSE' | 'INVENTORY_MANAGER' | 'ACCOUNTANT';
export type Permission = 'POS_CHECKOUT' | 'INVOICE_REFUND' | 'INVENTORY_TRANSFER_CREATE' | 'FINANCE_VIEW' | 'FINANCE_POST' | 'CRM_ASSIGN' | 'ATTENDANCE_REVIEW' | 'CHANNEL_MANAGE';

const aliases: Record<string, CanonicalRole> = {
  SALE: 'SALES', SALES: 'SALES',
  TECH: 'TECHNICIAN', TECHNICIAN: 'TECHNICIAN',
  CSKH: 'CUSTOMER_CARE', CUSTOMER_CARE: 'CUSTOMER_CARE'
};

export function normalizeRole(value: unknown): string {
  const role = String(value || '').trim().toUpperCase();
  return aliases[role] || role;
}

const grants: Partial<Record<CanonicalRole, Permission[]>> = {
  ADMIN: ['POS_CHECKOUT', 'INVOICE_REFUND', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'CRM_ASSIGN', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  REGIONAL_MANAGER: ['POS_CHECKOUT', 'INVOICE_REFUND', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'CRM_ASSIGN', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  MANAGER: ['POS_CHECKOUT', 'INVOICE_REFUND', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'CRM_ASSIGN', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  STORE_MANAGER: ['POS_CHECKOUT', 'INVOICE_REFUND', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'CRM_ASSIGN', 'ATTENDANCE_REVIEW'],
  SALES: ['POS_CHECKOUT'], SALE_ONLINE: ['POS_CHECKOUT'], CASHIER: ['POS_CHECKOUT'],
  ACCOUNTANT: ['FINANCE_VIEW', 'FINANCE_POST'],
  INVENTORY_MANAGER: ['INVENTORY_TRANSFER_CREATE'], WAREHOUSE: ['INVENTORY_TRANSFER_CREATE'],
  TECH_LEAD: ['INVENTORY_TRANSFER_CREATE'], TECHNICIAN: ['INVENTORY_TRANSFER_CREATE'], CUSTOMER_CARE: []
};

export function hasPermission(role: unknown, permission: Permission): boolean {
  const canonical = normalizeRole(role) as CanonicalRole;
  return Boolean(grants[canonical]?.includes(permission));
}
