export type CanonicalRole = 'ADMIN' | 'REGIONAL_MANAGER' | 'MANAGER' | 'STORE_MANAGER' | 'SALES' | 'SALE_ONLINE' | 'CUSTOMER_CARE' | 'TECHNICIAN' | 'TECH_LEAD' | 'CASHIER' | 'WAREHOUSE' | 'INVENTORY_MANAGER' | 'ACCOUNTANT';
export type Permission =
  | 'POS_CHECKOUT'
  | 'INVOICE_READ'
  | 'INVOICE_REFUND'
  | 'TRADE_IN_READ'
  | 'CRM_READ'
  | 'CRM_ASSIGN'
  | 'PARTNER_DIRECTORY_READ'
  | 'INVENTORY_TRANSFER_CREATE'
  | 'FINANCE_VIEW'
  | 'FINANCE_POST'
  | 'ATTENDANCE_REVIEW'
  | 'CHANNEL_MANAGE';

const aliases: Record<string, CanonicalRole> = {
  SALE: 'SALES', SALES: 'SALES',
  TECH: 'TECHNICIAN', TECHNICIAN: 'TECHNICIAN',
  CSKH: 'CUSTOMER_CARE', CUSTOMER_CARE: 'CUSTOMER_CARE'
};

export function normalizeRole(value: unknown): string {
  const role = String(value || '').trim().toUpperCase();
  return aliases[role] || role;
}

const grants: Partial<Record<CanonicalRole, Permission[]>> = {
  ADMIN: ['POS_CHECKOUT', 'INVOICE_READ', 'INVOICE_REFUND', 'TRADE_IN_READ', 'CRM_READ', 'CRM_ASSIGN', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  REGIONAL_MANAGER: ['POS_CHECKOUT', 'INVOICE_READ', 'INVOICE_REFUND', 'TRADE_IN_READ', 'CRM_READ', 'CRM_ASSIGN', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  MANAGER: ['POS_CHECKOUT', 'INVOICE_READ', 'INVOICE_REFUND', 'TRADE_IN_READ', 'CRM_READ', 'CRM_ASSIGN', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'FINANCE_POST', 'ATTENDANCE_REVIEW', 'CHANNEL_MANAGE'],
  STORE_MANAGER: ['POS_CHECKOUT', 'INVOICE_READ', 'INVOICE_REFUND', 'TRADE_IN_READ', 'CRM_READ', 'CRM_ASSIGN', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE', 'FINANCE_VIEW', 'ATTENDANCE_REVIEW'],
  SALES: ['POS_CHECKOUT', 'INVOICE_READ', 'TRADE_IN_READ', 'CRM_READ', 'PARTNER_DIRECTORY_READ'],
  SALE_ONLINE: ['POS_CHECKOUT', 'INVOICE_READ', 'TRADE_IN_READ', 'CRM_READ', 'PARTNER_DIRECTORY_READ'],
  CUSTOMER_CARE: ['INVOICE_READ', 'CRM_READ', 'PARTNER_DIRECTORY_READ'],
  CASHIER: ['POS_CHECKOUT', 'INVOICE_READ', 'PARTNER_DIRECTORY_READ'],
  ACCOUNTANT: ['INVOICE_READ', 'PARTNER_DIRECTORY_READ', 'FINANCE_VIEW', 'FINANCE_POST'],
  INVENTORY_MANAGER: ['INVOICE_READ', 'TRADE_IN_READ', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE'],
  WAREHOUSE: ['INVOICE_READ', 'TRADE_IN_READ', 'PARTNER_DIRECTORY_READ', 'INVENTORY_TRANSFER_CREATE'],
  TECH_LEAD: ['TRADE_IN_READ', 'INVENTORY_TRANSFER_CREATE'],
  TECHNICIAN: ['TRADE_IN_READ', 'INVENTORY_TRANSFER_CREATE']
};

export function hasPermission(role: unknown, permission: Permission): boolean {
  const canonical = normalizeRole(role) as CanonicalRole;
  return Boolean(grants[canonical]?.includes(permission));
}
